// Code generated by "stringer -type=Interest"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Interested-0]
	_ = x[NotInterested-1]
}

const _Interest_name = "InterestedNotInterested"

var _Interest_index = [...]uint8{0, 10, 23}

func (i Interest) String() string {
	if i >= Interest(len(_Interest_index)-1) {
		return "Interest(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interest_name[_Interest_index[i]:_Interest_index[i+1]]
}
