// Code generated by "stringer -type=connectionStatus"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionEstablished-0]
	_ = x[ConnectionKilled-1]
}

const _ConnectionStatus_name = "ConnectionEstablishedConnectionKilled"

var _ConnectionStatus_index = [...]uint8{0, 21, 37}

func (i ConnectionStatus) String() string {
	if i < 0 || i >= ConnectionStatus(len(_ConnectionStatus_index)-1) {
		return "connectionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionStatus_name[_ConnectionStatus_index[i]:_ConnectionStatus_index[i+1]]
}
