// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package messagesv1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeepAliveType - -1]
	_ = x[ChokeType-0]
	_ = x[UnChokeType-1]
	_ = x[InterestType-2]
	_ = x[NotInterestType-3]
	_ = x[HaveType-4]
	_ = x[BitfieldType-5]
	_ = x[RequestType-6]
	_ = x[PieceType-7]
	_ = x[CancelType-8]
	_ = x[PortType-9]
}

const _MessageType_name = "KeepAliveTypeChokeTypeUnChokeTypeInterestTypeNotInterestTypeHaveTypeBitfieldTypeRequestTypePieceTypeCancelTypePortType"

var _MessageType_index = [...]uint8{0, 13, 22, 33, 45, 60, 68, 80, 91, 100, 110, 118}

func (i MessageType) String() string {
	i -= -1
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
